### ISSUE TITLE
Why react and react-dom in dependencies?

### ISSUE THREAD

**Issue by voronianski** [fatiherikli/react-designer#3]
It seems unnecessary to keep React in dependencies, even more it can produce errors when 2 different version of React are used - https://github.com/fatiherikli/react-designer/blob/master/package.json#L45

The same goes for ReactDOM.

**Comment by tajo** [comment]
The best solution is to put `react` and `react-dom` to both peerDeps and devDev.

**Comment by voronianski** [comment]
I think it's fine to have it only in devDeps (for examples to work) and put info in readme when installing: `npm install react react-dom react-designer` (for newbies).

**Comment by fatiherikli** [comment]
Yeah, you're absolutely right. It should be in dev-dependencies

**Comment by fatiherikli** [comment]
This issue should be resolved with last release.

**Comment by voronianski** [comment]
@fatiherikli sorry but I still see these deps in your packag.json - https://github.com/fatiherikli/react-designer/blob/master/package.json#L45-L47

**Comment by fatiherikli** [comment]
Ops, sorry, this is my mistake

**Comment by voronianski** [comment]
@fatiherikli maybe you'll accept PR? this an easy change, but it's not updated almost a week.
